# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-31 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_combindemoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='imagehash',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
