# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-31 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_emoji_imagehash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emoji',
            name='imagehash',
        ),
        migrations.AddField(
            model_name='emoji',
            name='imagehash_str',
            field=models.TextField(blank=True, null=True),
        ),
    ]
